import { prisma } from "@/lib/prisma";
import { extractPdfText } from "@/lib/pdf-parser";
import fs from "fs";
import path from "path";

const AI_PARSERS_DIR = path.join(process.cwd(), "..", "parser", "parsers", "aiParsers");

type ParserField = {
  fieldName: string;
  labels: string[];
  valuePosition: "right";
};

export type ParserGenerationInput = {
  sourceType: "PAYSLIP" | "STATEMENT";
  payslipId?: string;
  statementId?: string;
  pdfText: string;
  rawFilename: string;
  bankName?: string;
  employerName?: string;
  parserFields: ParserField[];
};

function extractFormatSignature(pdfText: string): string {
  const lines = pdfText.split("\n").filter(Boolean);
  const markers: string[] = [];
  const seen = new Set<string>();
  for (const line of lines.slice(0, 80)) {
    const t = line.trim().toUpperCase().replace(/[^A-Za-zÁÉÍÓÚÑáéíóúñ0-9\s]/g, "");
    if (t.length < 3 || t.length > 100) continue;
    const key = t.slice(0, 40);
    if (!seen.has(key)) {
      seen.add(key);
      markers.push(key);
    }
  }
  return JSON.stringify(markers.slice(0, 30));
}

function escapePyString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t");
}

function generatePythonParser(input: ParserGenerationInput): string {
  const className = input.sourceType === "PAYSLIP"
    ? `AIPayslipParser_${(input.employerName ?? "unknown").replace(/[^a-zA-Z0-9]/g, "_")}`
    : `AIStatementParser_${(input.bankName ?? "unknown").replace(/[^a-zA-Z0-9]/g, "_")}`;

  const fieldLabelsCode = input.parserFields.length > 0
    ? input.parserFields.map((f) => {
        const labels = f.labels.map((l) => `"${escapePyString(l)}"`).join(", ");
        return `        "${f.fieldName}": [${labels}],`;
      }).join("\n")
    : "";

  const detectPattern = input.sourceType === "PAYSLIP"
    ? (input.employerName ?? "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    : (input.bankName ?? "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

  const hasFields = input.parserFields.length > 0;

  const payDateField = input.parserFields.find((f) => f.fieldName === "pay_date" || f.fieldName === "due_date");

  return `# Auto-generated by AI parser generator
# Source: ${input.rawFilename}
# Type: ${input.sourceType}
# Generated at: ${new Date().toISOString()}

import re
from parsers.base import BaseStatementParser
from models.schema import ParsedStatement, ParsedHeader, ParsedBalanceSummary, ParsedTransaction


class ${className}(BaseStatementParser):
    """AI-generated parser for ${escapePyString(input.rawFilename)}"""
${hasFields ? `
    # Labels detected by AI analysis for each field (including synonyms)
    _FIELD_LABELS = {
${fieldLabelsCode}
    }` : ""}

${hasFields ? `    @staticmethod
    def _clean_amount(raw: str) -> float:
        """Parse Argentine-format money string to float."""
        raw = raw.strip()
        # Remove currency symbols
        for sym in ["$", "ARS", "USD", "EUR", "U$S", "AR$", "US$"]:
            raw = raw.replace(sym, "")
        raw = raw.strip()
        if not raw:
            return 0.0
        # Handle comma-as-decimal (Argentine format: 1.234,56)
        if "," in raw and "." in raw:
            if raw.rfind(",") > raw.rfind("."):
                raw = raw.replace(".", "")
                raw = raw.replace(",", ".")
        elif "," in raw:
            raw = raw.replace(",", ".")
        elif "." in raw:
            parts = raw.split(".")
            if len(parts) > 2:
                raw = "".join(parts[:-1]) + "." + parts[-1]
        try:
            return float(raw)
        except ValueError:
            return 0.0

    def _extract_value(self, text: str, field_name: str) -> str:
        """Search lines for any label of field_name and return the value to its right."""
        labels = self._FIELD_LABELS.get(field_name, [])
        if not labels:
            return ""
        for line in text.split("\\n"):
            stripped = line.strip()
            upper_stripped = stripped.upper()
            for label in labels:
                label_upper = label.upper()
                pos = upper_stripped.find(label_upper)
                if pos < 0:
                    continue
                value_part = stripped[pos + len(label):].strip()
                if not value_part:
                    continue
                value_part = value_part.lstrip(":.-\\u2013\\u2014= ")
                if value_part:
                    return value_part
        return ""

    def _extract_date(self, text: str, field_name: str) -> str:
        raw = self._extract_value(text, field_name)
        if not raw:
            return ""
        # DD/MM/YYYY
        m = re.search(r"(\\d{1,2})/(\\d{1,2})/(\\d{4})", raw)
        if m:
            return f"{m.group(3)}-{m.group(2).zfill(2)}-{m.group(1).zfill(2)}"
        # DD-MM-YYYY
        m = re.search(r"(\\d{1,2})-(\\d{1,2})-(\\d{4})", raw)
        if m:
            return f"{m.group(3)}-{m.group(2).zfill(2)}-{m.group(1).zfill(2)}"
        # YYYY-MM-DD
        m = re.search(r"(\\d{4})-(\\d{1,2})-(\\d{1,2})", raw)
        if m:
            return m.group(0)
        return raw
` : ""}
    def detect(self, text: str) -> bool:
        """Check if this parser can handle the given PDF text."""
        ${hasFields
          ? `return bool(re.search(r"${detectPattern}", text, re.IGNORECASE))`
          : "return True"
        }

    def parse(self) -> ParsedStatement:
        text = self.full_text()
        ${hasFields ? `
        header = ParsedHeader(
            bank_name=self._extract_value(text, "bank_name"),
            holder_name=self._extract_value(text, "holder_name"),
            card_last_four=self._extract_value(text, "card_last_four"),
            card_network=self._extract_value(text, "card_network"),
            period_start=self._extract_date(text, "period_start"),
            period_end=self._extract_date(text, "period_end"),
            due_date=self._extract_date(text, "due_date"),
        )

        balance = ParsedBalanceSummary(
            previous_balance=self._clean_amount(self._extract_value(text, "previous_balance")),
            payments_applied=self._clean_amount(self._extract_value(text, "payments_applied")),
            total_consumption=self._clean_amount(self._extract_value(text, "total_consumption")),
            commission_cuenta_full=self._clean_amount(self._extract_value(text, "commission_cuenta_full")),
            sello_tax=self._clean_amount(self._extract_value(text, "sello_tax")),
            iva_tax=self._clean_amount(self._extract_value(text, "iva_tax")),
            iibb_tax=self._clean_amount(self._extract_value(text, "iibb_tax")),
            financing_interest=self._clean_amount(self._extract_value(text, "financing_interest")),
            current_balance=self._clean_amount(self._extract_value(text, "current_balance")),
            minimum_payment=self._clean_amount(self._extract_value(text, "minimum_payment")),
        )
        ` : `
        header = ParsedHeader(
            bank_name="${escapePyString(input.bankName ?? "Unknown")}",
            holder_name="",
            card_last_four="",
            card_network="",
            period_start="",
            period_end="",
            due_date="",
        )

        balance = ParsedBalanceSummary(
            previous_balance=0,
            payments_applied=0,
            total_consumption=0,
            commission_cuenta_full=0,
            sello_tax=0,
            iva_tax=0,
            iibb_tax=0,
            financing_interest=0,
            current_balance=0,
            minimum_payment=0,
        )
        `}

        transactions: list[ParsedTransaction] = []

        return ParsedStatement(
            header=header,
            balance_summary=balance,
            transactions=transactions,
            parser_version="ai-generated-v1",
        )
`;
}

export function saveAiParserFile(id: string, code: string): string {
  try {
    fs.mkdirSync(AI_PARSERS_DIR, { recursive: true });
    const filePath = path.join(AI_PARSERS_DIR, `${id}.py`);
    fs.writeFileSync(filePath, code, "utf-8");
    return filePath;
  } catch {
    return "";
  }
}

export function readAiParserFile(parserId: string): string {
  const filePath = path.join(AI_PARSERS_DIR, `${parserId}.py`);
  if (!fs.existsSync(filePath)) throw new Error("Parser file not found");
  return fs.readFileSync(filePath, "utf-8");
}

export async function createAiParserFromAnalysis(input: ParserGenerationInput): Promise<string> {
  const parserCode = generatePythonParser(input);
  const formatSignature = extractFormatSignature(input.pdfText);

  const aiParser = await prisma.aiParser.create({
    data: {
      payslipId: input.payslipId ?? null,
      statementId: input.statementId ?? null,
      parserCode,
      filePath: "",
      formatSignature,
      sourceType: input.sourceType,
      bankName: input.bankName ?? null,
      employerName: input.employerName ?? null,
      status: "PENDING_REVIEW",
    },
  });

  const filePath = saveAiParserFile(aiParser.id, parserCode);

  await prisma.aiParser.update({
    where: { id: aiParser.id },
    data: { filePath },
  });

  return aiParser.id;
}

export async function findMatchingAiParsers(pdfText: string, sourceType: "PAYSLIP" | "STATEMENT"): Promise<Array<{ id: string; parserCode: string; bankName: string | null; employerName: string | null }>> {
  const signature = extractFormatSignature(pdfText);
  const parsers = await prisma.aiParser.findMany({
    where: {
      sourceType,
      status: "APPROVED",
    },
    select: {
      id: true,
      parserCode: true,
      bankName: true,
      employerName: true,
      formatSignature: true,
    },
  });

  const incomingSignature: string[] = JSON.parse(signature);
  const candidates: Array<{ id: string; parserCode: string; bankName: string | null; employerName: string | null; score: number }> = [];

  for (const p of parsers) {
    const storedSignature: string[] = JSON.parse(p.formatSignature);
    const overlap = incomingSignature.filter((s) => storedSignature.includes(s)).length;
    const score = storedSignature.length > 0 ? overlap / storedSignature.length : 0;
    if (score >= 0.4) {
      candidates.push({ id: p.id, parserCode: p.parserCode, bankName: p.bankName, employerName: p.employerName, score });
    }
  }

  candidates.sort((a, b) => b.score - a.score);
  return candidates.slice(0, 3);
}
